[features]
seeds = false
skip-lint = false


[registry]
url = "https://api.apr.dev"

[programs.devnet]
bounty = "BoUNtye7MsbG3rWSXxgXTyWt2Q7veUrKwWeDJo7BED3e"

[programs.mainnet]
bounty = "BoUNtye7MsbG3rWSXxgXTyWt2Q7veUrKwWeDJo7BED3e"

[programs.localnet]
bounty = "BoUNtye7MsbG3rWSXxgXTyWt2Q7veUrKwWeDJo7BED3e"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build_sdk = "cd sdk-ts && yarn build"
test_alt = "rm -rf test-ledger && solana-test-validator --reset -q"


[test.validator]
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/fixtures/metadata_program.bpf"
