[features]
seeds = false
skip-lint = false


[registry]
url = "https://api.apr.dev"

[programs.devnet]
bounty = "SANdemMWicpWGcrX9HiNn33dqGGktwA7q2fnbp9aWpo"

[programs.mainnet]
bounty = "SANdemMWicpWGcrX9HiNn33dqGGktwA7q2fnbp9aWpo"

[programs.localnet]
bounty = "SANdemMWicpWGcrX9HiNn33dqGGktwA7q2fnbp9aWpo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
