[features]
seeds = false
skip-lint = false


[registry]
url = "https://api.apr.dev"

[programs.devnet]
bounty = "HELsfudvMchbrYGCFiBPwGp5eXt2kwoPLKDVByy4cLzd"

[programs.mainnet]
bounty = "HELsfudvMchbrYGCFiBPwGp5eXt2kwoPLKDVByy4cLzd"

[programs.localnet]
bounty = "HELsfudvMchbrYGCFiBPwGp5eXt2kwoPLKDVByy4cLzd"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
