version: '3.0'
services:
  relayer:
    image: relayer
    build: 
      context: "."
      dockerfile: dockerfile.relayer
    volumes: 
      - ./programs:/programs
  dapp:
    image: dapp
    build: 
      context: "."
      dockerfile: dockerfile.dapp
      target: deploy-node
    ports: 
      - 3000:3000 
  solana:
    image: werbitt/solana-test-validator
    ports: 
      - 8899:8899
