version: '3.0'
services:
  relayer:
    image: relayer
    build: 
      context: "."
      dockerfile: dockerfile.relayer
    env_file:
      - .env.local
    volumes: 
      - ./programs:/programs
  dapp:
    image: dapp
    build: 
      context: "."
      dockerfile: dockerfile.dapp
      target: deploy-node
    env_file:
      - .env.local
    ports: 
      - 3000:3000 