
FROM node:18-alpine AS build

WORKDIR /dapp
COPY /sdk-ts/ ./../sdk-ts
COPY ./dapp/ /dapp/
COPY ./../.yarn ./../.yarn
COPY ./../.yarnrc.yml ./../.yarnrc.yml
COPY ./../.yarnrc ./../.yarnrc
COPY ./../package.json ./../package.json
RUN yarn
RUN yarn build

FROM node:18-alpine AS deploy-node
WORKDIR /dapp
RUN rm -rf ./*
COPY --from=build /dapp/ /dapp/
CMD ["node","build/index.js"]