FROM rust:1.66.1 as build

WORKDIR /rewards
COPY Cargo.toml .
COPY Anchor.toml .
ADD programs programs
ADD relayer relayer
ADD cli cli
ADD sdk sdk
RUN cargo build --release --package relayer

FROM rust:1.66.1-slim-buster
WORKDIR /relayer
COPY --from=build /rewards/target/ /relayer/target

CMD ["./target/release/relayer"]