FROM node:18-alpine AS build

ENV SDK_VERSION="1.0.3"
ADD target target

COPY /nginx/nginx.conf /nginx/nginx.conf
WORKDIR /dapp/
COPY ./app /dapp/
RUN yarn
RUN yarn build

FROM nginx
COPY --from=build /dapp/dist/ /usr/share/nginx/html
COPY --from=build /nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
