[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rewards = {path="../programs/rewards-v1"}
anchor-spl = "0.24.2"
anchor-client = "0.24.2"
octocrab = "0.18.1"
